INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_CLASSIFIER classifier)

FIND_PATH(
    CLASSIFIER_INCLUDE_DIRS
    NAMES classifier/api.h
    HINTS $ENV{CLASSIFIER_DIR}/include
        ${PC_CLASSIFIER_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    CLASSIFIER_LIBRARIES
    NAMES gnuradio-classifier
    HINTS $ENV{CLASSIFIER_DIR}/lib
        ${PC_CLASSIFIER_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(CLASSIFIER DEFAULT_MSG CLASSIFIER_LIBRARIES CLASSIFIER_INCLUDE_DIRS)
MARK_AS_ADVANCED(CLASSIFIER_LIBRARIES CLASSIFIER_INCLUDE_DIRS)

